In [2]:
import numpy as np

In [15]:
chi_grid=np.zeros((L,L))
chi_grid[0,0]=1e6 #placeholder
print(chi_grid)

[[1000000.       0.       0. ...       0.       0.       0.]
 [      0.       0.       0. ...       0.       0.       0.]
 [      0.       0.       0. ...       0.       0.       0.]
 ...
 [      0.       0.       0. ...       0.       0.       0.]
 [      0.       0.       0. ...       0.       0.       0.]
 [      0.       0.       0. ...       0.       0.       0.]]


In [13]:
liste=np.zeros((0,10))
lista = np.array([1,2])
listb = np.array([3,4])
print(liste)
print(np.min(liste))
print(liste[1,1])

IndexError: index 0 is out of bounds for axis 0 with size 0